/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function main(): void;
export function sixtyfps_component_window_init(a: number): void;
export function sixtyfps_property_init(a: number): void;
export function sixtyfps_property_update(a: number, b: number): void;
export function sixtyfps_property_set_changed(a: number, b: number): void;
export function sixtyfps_property_set_binding(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function sixtyfps_property_set_binding_internal(a: number, b: number): void;
export function sixtyfps_property_is_dirty(a: number): number;
export function sixtyfps_property_drop(a: number): void;
export function sixtyfps_property_set_animated_value_int(a: number, b: number, c: number, d: number): void;
export function sixtyfps_property_set_animated_value_float(a: number, b: number, c: number, d: number): void;
export function sixtyfps_property_set_animated_value_color(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): void;
export function sixtyfps_property_set_animated_binding_int(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function sixtyfps_property_set_animated_binding_float(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function sixtyfps_property_set_animated_binding_color(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function sixtyfps_property_set_state_binding(a: number, b: number, c: number, d: number): void;
export function sixtyfps_property_tracker_init(a: number): void;
export function sixtyfps_property_tracker_evaluate(a: number, b: number, c: number): void;
export function sixtyfps_property_tracker_is_dirty(a: number): number;
export function sixtyfps_property_tracker_drop(a: number): void;
export function sixtyfps_component_window_drop(a: number): void;
export function sixtyfps_component_window_clone(a: number, b: number): void;
export function sixtyfps_component_window_run(a: number): void;
export function sixtyfps_component_window_get_scale_factor(a: number): number;
export function sixtyfps_component_window_set_scale_factor(a: number, b: number): void;
export function sixtyfps_component_window_free_graphics_resources(a: number, b: number): void;
export function sixtyfps_component_window_set_focus_item(a: number, b: number): void;
export function sixtyfps_component_window_set_component(a: number, b: number): void;
export function sixtyfps_component_window_show_popup(a: number, b: number, c: number, d: number): void;
export function sixtyfps_signal_init(a: number): void;
export function sixtyfps_signal_emit(a: number, b: number): void;
export function sixtyfps_signal_set_handler(a: number, b: number, c: number, d: number): void;
export function sixtyfps_signal_drop(a: number): void;
export function sixtyfps_timer_start(a: number, b: number, c: number, d: number): number;
export function sixtyfps_timer_singleshot(a: number, b: number, c: number, d: number): void;
export function sixtyfps_timer_stop(a: number): void;
export function sixtyfps_mock_elapsed_time(a: number): void;
export function sixtyfps_shared_array_empty(): number;
export function solve_grid_layout(a: number): void;
export function sixtyfps_visit_item_tree(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): number;
export function sixtyfps_new_path_elements(a: number, b: number, c: number): void;
export function sixtyfps_shared_string_bytes(a: number): number;
export function sixtyfps_component_init_items(a: number, b: number, c: number, d: number, e: number): void;
export function sixtyfps_item_offset(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function sixtyfps_send_mouse_click(a: number, b: number, c: number, d: number): void;
export function sixtyfps_set_keyboard_modifiers(a: number, b: number): void;
export function sixtyfps_send_key_clicks(a: number, b: number): void;
export function send_keyboard_string_sequence(a: number, b: number): void;
export function sixtyfps_new_path_events(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function sixtyfps_shared_array_allocate(a: number, b: number): number;
export function sixtyfps_shared_array_free(a: number, b: number, c: number): void;
export function grid_layout_info(a: number, b: number, c: number, d: number): void;
export function solve_box_layout(a: number, b: number): void;
export function box_layout_info(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function solve_path_layout(a: number): void;
export function sixtyfps_shared_string_drop(a: number): void;
export function sixtyfps_shared_string_clone(a: number, b: number): void;
export function sixtyfps_shared_string_from_bytes(a: number, b: number, c: number): void;
export function sixtyfps_shared_string_from_number(a: number, b: number): void;
export function sixtyfps_shared_string_append(a: number, b: number, c: number): void;
export function sixtyfps_flickable_data_init(a: number): void;
export function sixtyfps_flickable_data_free(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h073eddf56cbd187d(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h9220e625399cab4e(a: number, b: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h60a9b49fcbb9dbb8(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h06832a9ac2bec42b(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_start(): void;
